antlr/3.2/libantlr3c-3.2/src/antlr3filestream.c
gc/cord/cord.am
gc/win32_threads.c

- remove special Windows handling of files in antlr/3.2/libantlr3c-3.2/src/antlr3filestream.c
- rename libgc.la to libomcgc.la in gc/cord/cord.am
- disable usage of pthreads for GC parallel marking in gc/win32_threads.c

Fixes for ticket:3955

---

lpsolve/configure.ac
lpsolve/lp_types.h

- fix library name to be liblpsolve55.dll not liblpsolve55.so
- fix INLINE definition for mingw

fixes for MINGW

---

CMakeLists.txt
gc/CMakeLists.txt

- gc is named omcgc. This was done for the library built by
autotools config. So we will do it here as well.
I am guessing this is done so that we would not link to installed
gc inadvertently.

[cmake] Rename libgc to libomcgc.

---

FMIL/ThirdParty/Expat/expat-2.1.0/CMakeLists.txt

- Use CMAKE_CURRENT_BINARY_DIR instead of CMAKE_BINARY_DIR.
CMAKE_CURRENT_BINARY_DIR is the build directory corresponding
to the folder where the current CMakeLists.txt is located.
CMAKE_BINARY_DIR points to the TOP build directory. Which might not
be the same as the former if the project is added as part of another
parent project structure.

[cmake] Fix include directory for expat.

---

CMinpack/cmake/CMakeLists.txt
FMIL/CMakeLists.txt

- It might not be possible to write to the ${CMAKE_ROOT} directory due
to permissions. So for now we skip the installation of the
FindCMinpack.cmake module.
- FMIL! it is just bad. They change the installation prefix internally,
add it to the cache and even force overwriting it to their own
selected installation prefix. Just remove that part.

[cmake] Fix FMIL and CMinpack for installation.

---

FMIL/CMakeLists.txt

- Use the user specified installation directory. Do not make internal
decisions on where to install. Leave that to the user.

[cmake] More fix for FMI library installation.

---

libzmq/CMakeLists.txt

- There are more libraries needed to link when linking to libzmq-static
on Windows, i.e transitive dependencies for users of libzmq-static.

[cmake] libzmq-static depends on more libs on Win.

---

FMIL/ThirdParty/Minizip/minizip/miniunz.c

miniunz.c:143:11: error: implicit declaration of function 'mkdir' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

attempt to fix Mac build #6136

---

CMakeLists.txt
gc/CMakeLists.txt

- Add missing gc_dlopen.c to configuration.
- The source file _gc_dlopen.c_ is not listed in the SRC variable of the
CMake configuration. This leads to undefined references of GC_dlopen
when the library is built as a STATIC library.
- When building as shared library it does not happen because the SRC
variable listing all source files is overridden to contain only the
single source extra/gc.c (which I assume contains the missing definition
- Build Boehm GC as a static library as well
- We now build gc as a static lib. This means there are no more shared
libraries in compilation of omc (except libOpenModelicaCompiler itself
if needed of course.)
- This also means there is no need to install it with omc for using just
omc. You will have to install it to use it with simulation executables
of …

Fix boehm GC gc_dlopen() undef. referrnce and build as static lib 

---

CMakeLists.txt
antlr/3.2/libantlr3c-3.2/CMakeLists.txt

@mahge
Improve cmake support of antlr3.
da03519
- Do a proper check of all the required headers and sub-standard functions
needed.
- Define the corresponding HAVE_* variables.
- Generate an atlr3config.h header from cmake (corresponding to the
auto conf one.)
Note the antlr3config.h from cmake is generated in the include/
directory.
@mahge
Workaround for FMIL's unusual structure.
51e6cee
- We now collect all the public include files of FMIL into one top
level include folder. The structure of this folder matches the
'installed' include folders of FMIL. We make ONLY this include dir
for our libraries that depend on FMIL.
- Shared builds of fmilib are disabled now. You can enable them if you
really need them.

Cmake bootstrapping

---

CMakeLists.txt
antlr/3.2/libantlr3c-3.2/CMakeLists.txt
antlr/3.2/libantlr3c-3.2/antlr3config.h.in.cmake

@mahge
Improve cmake support of antlr3.
375a2c4
- Do a proper check of all the required headers and sub-standard functions
needed.
- Define the corresponding HAVE_* variables.
- Generate an atlr3config.h header from cmake (corresponding to the
auto conf one.)
Note the antlr3config.h from cmake is generated in the include/
directory.
@mahge
Workaround for FMIL's unusual structure.
ef6cc71
- We now collect all the public include files of FMIL into one top
level include folder. The structure of this folder matches the
'installed' include folders of FMIL. We make ONLY this include dir
for our libraries that depend on FMIL.
- Shared builds of fmilib are disabled now (only for the new CMake build. Normal compilation is not affected). You can enable them if you really need them.

CMake improvments to 3rdParty libraries.

---

CMakeLists.txt

- lp_solve needs bison and flex. These are not available in our
build-dep packages or docker files we distribute. So make this optional
for now.

Make building lp_solve optional.

---

CMakeLists.txt

- There is no need to build (and install) them.

[cmake] Disable building of sundials examples.

---

CMakeLists.txt
sundials-5.4.0/config/SundialsKLU.cmake

- There is no need to check if a small file that just includes suitsparse
can be compiled. We have SuiteSparse in our sources. It will work.
The problem with the check is that it expects SuiteSparse to be already
built. We do not want that. It is intended to be used with installed
or already pre-built SuiteSparse.
For us, at configure time we just want to tell Sundials that we have
SuiteSparse and we will build it. It should just assume it works.

Disable sundials's check of usability of suitsparse

---

Ipopt-3.13.4/cmake/coin-macros.cmake

- The docker images we use for normal CI build (e.g. for testing PRs)
have python. However it is not really an official requirement for
building OpenModelica. Hence the scripts we use for the nightly
builds (e.g el7, el8) do not list it as requirement. So some of the
nightly build images do not have Python in them.
- It is only needed for reporting test results. We do not use the testing
at all anyway.
- There is no Ipopt option to disable tests. So for now do it
manually.

Make Ipopt's Python requirement optional.

---

CMakeLists.txt
lis-1.4.12/src/CMakeLists.txt

@mahge
[cmake] Disable sundials shared libs. …
60b590c
- Note! This does not affect the normal OpenModelica makefile build
process. This is just for the new CMake config and build.
- They are not needed per se. It is a waste to build both shared and
static versions at the same time.
@mahge
[cmake] Install liblis. …
4706572
- Probably not needed. But the makefiles build system installs it so
we do it for now.
@mahge
[cmake] Handle Ipopt's public headers. …
10645db
- Just like FMIL, Ipopt assumes it will be always installed before use.
So it does not organize its header files properly.
We collect all public headers to a new include dir in the build directory
of Ipopt. Then we provide this new directory as include dir for targets
that depend on Ipopt.

CMake improvements

---

CMakeLists.txt

@mahge
[cmake] Alias for expat, remove ::static suffixes …
e620e46
- Expat is needed for libSimulationRuntimeC.
We use the expat from FMIL (since it is available and built there)
- Remove the ::static suffix from libraries since our default build
target type is static libraries by default. We do not build anything
as shared library now (at least not intentionally.)
There will be few shared libs later. For collecting the static libs
and providing all the functionality in one library. But that is special
and our intention is not to build any individual libs as shared libs.
@mahge
[cmake] Add aliases for more Sundials libs. …
ffc0934
- Also factorize the include directory providing a little bit. See the
comments in the code.

Add more aliases and remove ::static suffixes

---

sundials-5.4.0/include/kinsol/kinsol_impl.h
sundials-5.4.0/src/kinsol/CMakeLists.txt

- We should not be using internal headers of Kinsol. There is an interface
specifically for specifying the linear solver for Kinsol. We should
use that instead.
- Revert this when #7959 is fixed.

For now install kinsol_impl.h until #7959 is fixed

---

CMakeLists.txt

- Add a new interface library sundials_interface_static that adds the
define LINK_SUNDIALS_STATIC.
It brings the include directories by linking to sundials_interface
then adds the define.
All libs that will link to static sundails libs will now get the
define automatically.
If we need to link to the shared sundails libs at any point just
add a new interface library or use the sundials_interface library
itself since it does not add the define.

[cmake] define LINK_SUNDIALS_STATIC for static.

---

CMakeLists.txt

- Now that omc's dependency on ModelicaExternalC is removed, we do not
link them in anymore.
So zlib needs to be added itself to the linking. Previously it was
linked transitively through ModelicaMatIO

Add an alias for zlib.

---

antlr/3.2/libantlr3c-3.2/include/antlr3defs.h

- These two can not used be simultaneously. The rest of our code (e.g. our
parsers) use winsock2.h.
winsock2.h is backwards compatible with winsock.h. Use it as we are
not possibly targeting anything that does not have winsock2 support.

Use winsock2.h instead of winsock.h

---

CMakeLists.txt

- Disable Fortran dependent sundials library if Fortran is disabled from
OpenModelica build.
- Add Ipopt only if WITH_IPOPT is set. WITH_IPOPT can not be set if Fortran
support is disabled.

Towards making Fortran optional.

---

CMakeLists.txt
FMIL/Config.cmake/Minizip/CMakeLists.txt
gc/CMakeLists.txt
libffi/include/ffi.h.in
metis-5.1.0/GKlib/gk_arch.h

[Improve GC compilation portability.](https://github.com/OpenModelica/OMCompiler-3rdParty/commit/4fec01680abc6346bf2b7b9d0c779cb007e11cde) 
- Fix the configuration so that it can be compiled fine on MSVC. It needs
special treatment since we want it to use PThreads on all platoforms
including Windows with MSVC.
- On Windows with MSVC it now expects to have the PThreads4W library.
- Built-in atomic intrinsics are not available with MSVC. Make sure the
configuration reflects that for MSVC.
- Cover cases where it was only expecting MinGW on Windows and not MSVC.
@[mahge](https://github.com/OpenModelica/OMCompiler-3rdParty/commits?author=mahge)
mahge committed 4 hours ago
[Minor fixes for portability.](https://github.com/OpenModelica/OMCompiler-3rdParty/commit/a9c20f31d05977bf234042e5b36b815721 …

Minor fixes for portability.

---

gc/CMakeLists.txt

- Use `target_compile_definitions(...)` instead of just `add_definitions()`.
This allows us to add defines in a way that can apply transitively on
targets that link to `omcgc`. For example, GC_DLL or GC_NOT_DLL need to
be defined accordingly on anything that links to `omcgc` and includes the
header `gc.h`. Otherwise we will have inconsistencies on the attributes
used to declare functions when GC is built versus when GC is used.
- It is probably a good idea to fix all the other defines this way. We
just need to figure out which ones need to actually be PUBLIC (transitive)
and which ones are only needed to compiling `omcgc`.
- Disable build of GC's cord library. We do not use it.

Improve GC configuration.

---

CMakeLists.txt
FMIL/ThirdParty/Expat/expat-2.1.0/CMakeLists.txt

[Enable sunlinsollapackdense even with no Fortran support.](https://github.com/OpenModelica/OMCompiler-3rdParty/commit/d0abfbf97025030a4385e1711da82ad10088dd72) 
- The only reason sundails wants to have Fortran support to enable
`sunlinsollapackdense` is that it wants to figure out Fortran the name
mangling scheme so that it can use the Lapack libraries needed.
As it happens we can actually manually specify the name mangling scheme
to avoid the requirement for a Fortran compiler.
Thank you Sundails for being all around very well designed.
[Define XML_STATIC when linking to statick expat.](https://github.com/OpenModelica/OMCompiler-3rdParty/commit/a7400272ce802c8edf2a493bd5ec7e3e056149f6) 
- The define must be used when compiling any library that links to the
static version of libexpat to …

Enable sunlinsollapackdense even with no Fortran support.

---

gc/configure.ac

- This was working fine for static version of `libomcgc` because it did
not matter if the library was not found.
However for the dynamic version `libtool` complains that it is not
available and refuses to build the DLL on Windows.
clang does not need (or even allow) `-lpthread` as it appears. So do not
add it to the link command if we are using clang. If we are using gcc
then it should be added.

Do not add -lpthread if clang.

---

gc/CMakeLists.txt
gc/include/gc_config_macros.h

- GC has a setting where it gets compiled as a single file (a file that
includes all source files). According to the logs of the upstream GC
repository this is done to enable more optimizations.
It also enabled this one-file form when it was asked to build a shared
library with CMake. Even if it was not asked for explicitly.
However, the markup for the functions was missing the `extern` keyword
which leads to some confusing duplicate declaration errors.
Add the `extern` specifier. But **also disable the automatic one-file
compilation for shared version** behavior since the autoconf build does
not enable it unless it is asked for explicitly.
We are trying to be consistent to avoid ANY surprises with this useful
(I admit) but so very intrusive and infuriating library.

Fix compilation on OMDev/MinGW with CMake.

---

libffi/configure.ac

- Disable the setting of optimization flags. automatically by libffi's
own decisions. For OpenModelica we want to pass the options and flags
ourselves.
This was ignoring all CFLAGS we pass to libffi including `-fPIC`
breaking the build of OpenModelica on Fedora 36 because the libray
could not be linked to a shared library (since it was not compiled as
position independent code.)

libffi: disable autosetting of optimization flags.

---

libffi/include/fficonfig_cmake.h.in

- The preprocessor variable FFI_EXEC_TRAMPOLINE_TABLE should be defined
with a value. Either 0 or 1.
- On almost all systems we supported so far this was undefined completely
so it did not cause any issues.
- With `macOS` on `aarch64` systems (like the M1 mac) libffi wants this to
be "on". The CMake configuration was defining it to nothing, i.e.,
```c
#define FFI_EXEC_TRAMPOLINE_TABLE
```
and then compilation fails because the sources contain checks like
```c
#if FFI_EXEC_TRAMPOLINE_TABLE
```
which expect a value.
Always define it either to 0 or 1. If it is to be "defined" it should
be
```c
#if FFI_EXEC_TRAMPOLINE_TABLE 1
```
To be honest I am not sure if I completely understood how libffi wants
to use this variable. But looking at the way their sources use this
variable it seems like …

[libffi] Fix config header preprocessor definition.

---

lis-1.4.12/src/Makefile.am
lis-1.4.12/src/Makefile.in

- It refuses to build a shared library on Windows if this option is not set.
- This was never an issue for us because we were using `lis` from MinGW itself (`pacman` managed). We only used the 3rdParty version when building on Linux.
Now we want to switch to building from source because recent versions of mingw64-lis require MPI support and we do not want that.

Add -no-undefined to satisfy libtool on Windows.

---

Ipopt-3.13.4/ThirdParty/MUMPS/CMakeLists.txt

- `pthread` might not (probably never) be a valid compilation option. It is either `-pthread`, `-pthreads` or nothing mostly. Use the info from CMakes detection.

Let CMake decide what to use for pthread

---

FMIL/ThirdParty/Expat/expat-2.1.0/CMakeLists.txt

- The 3rdParty expat we have (inside FMIL) was probably using system headers because it did not specify include directories properly.
- We really need to find an alternative to FMIL. It is not feasible to continue fixing all these problems that it brings with it.

Make sure 3rdParty expat uses its own headers.

---

CMakeLists.txt
metis-5.1.0/libmetis/CMakeLists.txt

- Using pcreposix creates (fixable) issue with the old MSVC build of OpenModelica which wants to use 3rdParty/regex. It is just an include file name issue but maybe it is better to stick to what we already have for now. We can change it later.
- Build and make available the 3rdParty/regex code as the static library `omcregex` (for the CMake build.)

Use our 3rdParty/regex code instead of pcreposix.

---

CMakeLists.txt

- It has some portability issues (for macOS). Probably can be fixed but it is not going to be used on those systems anyway.

Build omcregex only for MSVC.

---

CMakeLists.txt
libffi/CMakeLists.txt

- This library is currently needed by the CPP runtime.
- Fix some issues with libffi config.
- A listed file name was missing an extension.
- A non existent directory was specified as an include dir.

Add alias for sundials IDA.

---

ryu/ryu/om_format.c

Somtimes 1.0 is badly rounded as 9.999999999 and then rounded to 10.000000000000, which is not good because it has two digits before the decimal point. This commit takes care of this corner case.

Fixed bad rounding of 9.9999999999

---

FMIL/ThirdParty/Minizip/minizip/zip.c

This is because fc40 has issues:
OMCompiler/3rdParty/FMIL/ThirdParty/Minizip/minizip/zip.c: In function ‘zipOpenNewFileInZip4_64’:
OMCompiler/3rdParty/FMIL/ThirdParty/Minizip/minizip/zip.c:1249:28: error: assignment to ‘const long unsigned int *’ from incompatible pointer type ‘const z_crc_t *’ {aka ‘const unsigned int *’} [-Wincompatible-pointer-types]
1249 |         zi->ci.pcrc_32_tab = get_crc_table();

cast to proper type

---

moo-0.1.0/CMakeLists.txt

- fixes ninja build https://github.com/OpenModelica/OpenModelica/issues/14276
- sets make program for MOO's legacy third-party builds
- falls back to $ENV{MAKE} or find_program(make)
Credits: @Dr-Zero, branch bugfix/moo-makeprogram-variable

[MOO] add MOO_MAKE_PROGRAM option for third-party builds / fix ninja build

---

moo-0.1.0/CMakeLists.txt

- forgot to add LAPACK path back to configure of MUMPS and Ipopt, partial revert of last commit

[MOO] add LAPACK path for configure

---

moo-0.1.0/CMakeLists.txt

- revert one change from the last commit; will reintroduce that feature later.
- setting C, CXX and Fortran compilers for configure works on Linux, but on Windows the 
different path system breaks the MUMPS and Ipopt builds

[MOO] revert setting configure compiler from CMake compiler
